version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6

commands:
  deploy-command:
    parameters:
      BRANCH:
        type: string
      HEROKU_APP_NAME:
        type: string
    steps:
      - run: heroku config:set YARN_PRODUCTION=false -a <<parameters.HEROKU_APP_NAME>>
      - run: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/<<parameters.HEROKU_APP_NAME>>.git <<parameters.BRANCH>>:main

jobs:
  build: # this can be any name you choose
    docker:
      - image: node:16
    resource_class: large
    parallelism: 10

    steps:
      - checkout

      - restore_cache:
          name: Restore pnpm Package Cache
          keys:
            - pnpm-packages-{{ checksum "package-lock.json" }}

      - run:
          name: Build app
          command: |
            npm install
            npm run build

      - save_cache:
          name: Save pnpm Package Cache
          key: package-lock-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      - persist_to_workspace:
          paths:
            - '.'
          root: ~/project

  test: # this can be any name you choose
    docker:
      - image: node:16
    resource_class: large
    parallelism: 10

    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/project/

      - run:
          name: Test app
          command: npm run test

  deploy:
    executor: heroku/default

    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: ~/project/

      - heroku/install

      - when:
          condition:
            equal: [master, << pipeline.git.branch >>]
          steps:
            - deploy-command:
                HEROKU_APP_NAME: joke-app-dc
                BRANCH: master

workflows:
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
